Update UserData to avoid permission errors with logging

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -80,51 +80,51 @@ Resources:
         Fn::Base64: !Sub |
           #!/bin/bash -xe
 
-          # send script output to /tmp so we can debug boot failures
-          exec > /tmp/userdata.log 2>&1
+          # send script output to /home/ec2-user so we can debug boot failures
+          exec > /home/ec2-user/userdata.log 2>&1
 
-          echo "Updating all packages..." >> /tmp/userdata.log
-          yum -y update >> /tmp/userdata.log 2>&1
+          echo 'Updating all packages...'
+          yum -y update
 
-          echo "Installing CloudFormation helper scripts..." >> /tmp/userdata.log
-          yum install -y aws-cfn-bootstrap >> /tmp/userdata.log 2>&1
+          echo 'Installing CloudFormation helper scripts...'
+          yum install -y aws-cfn-bootstrap
 
-          echo "Initializing CloudFormation resources..." >> /tmp/userdata.log
-          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance >> /tmp/userdata.log 2>&1
+          echo 'Initializing CloudFormation resources...'
+          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
 
           cat > /tmp/install_script.sh << EOF
             # START
-            echo "Setting up NodeJS Environment" >> /tmp/userdata.log
-            curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash >> /tmp/userdata.log 2>&1
+            echo "Setting up NodeJS Environment"
+            curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
 
             # Dot source the files to ensure that variables are available within the current shell
-            . /home/ec2-user/.nvm/nvm.sh >> /tmp/userdata.log 2>&1
-            . /home/ec2-user/.bashrc >> /tmp/userdata.log 2>&1
+            . /home/ec2-user/.nvm/nvm.sh
+            . /home/ec2-user/.bashrc
 
-            echo "Installing Node.js..." >> /tmp/userdata.log
-            nvm alias default v12.7.0 >> /tmp/userdata.log 2>&1
-            nvm install v12.7.0 >> /tmp/userdata.log 2>&1
-            nvm use v12.7.0 >> /tmp/userdata.log 2>&1
+            # Install NVM, NPM, Node.JS
+            nvm alias default v12.7.0
+            nvm install v12.7.0
+            nvm use v12.7.0
 
-            echo "Downloading and setting up application..." >> /tmp/userdata.log
-            wget https://github.com/ozcli/aws-bootstrap/archive/master.zip >> /tmp/userdata.log 2>&1
-            unzip master.zip >> /tmp/userdata.log 2>&1
-            mv aws-bootstrap-master app >> /tmp/userdata.log 2>&1
+            # Download latest code, unzip it into /home/ec2-user/app
+            wget https://github.com/ozcli/aws-bootstrap/archive/master.zip
+            unzip master.zip
+            mv aws-bootstrap-master app
 
-            echo "Creating log directory..." >> /tmp/userdata.log
-            mkdir -p /home/ec2-user/app/logs >> /tmp/userdata.log 2>&1
+            # Create log directory
+            mkdir -p /home/ec2-user/app/logs
 
-            echo "Running server..." >> /tmp/userdata.log
-            cd app >> /tmp/userdata.log 2>&1
-            npm install >> /tmp/userdata.log 2>&1
-            npm start >> /tmp/userdata.log 2>&1
+            # Run server
+            cd app
+            npm install
+            npm start
           EOF
 
-          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh >> /tmp/userdata.log 2>&1
-          sleep 1; su - ec2-user -c "/tmp/install_script.sh" >> /tmp/userdata.log 2>&1
+          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+          sleep 1; su - ec2-user -c "/tmp/install_script.sh"
 
-          echo "Sending signal to CloudFormation..." >> /tmp/userdata.log
-          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance >> /tmp/userdata.log 2>&1
+          # Signal to CloudFormation that the instance is ready
+          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
 
       Tags:
         - Key: Name
